language: node_js
deploy:
- provider: codedeploy
  revision_type: github
  access_key_id: AKIAJ5RL7WXLQ6SKAHQA
  secret_access_key: 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
  application: BlueGreenDemoApplication
  deployment_group: BlueGreenDemoFleet-n0tpx0i
  region: us-west-2